export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_AMOUNT_OF_QUESTIONS = "CHANGE_AMOUNT_OF_QUESTIONS";
export const CHANGE_SCORE = "CHANGE_SCORE";
